### ISSUE TITLE
Is there a way to make Policy more dynamic ?

### ISSUE THREAD

**Issue by ayushagarwal181** [phongnguyend/Practical.CleanArchitecture#123]
Is there a way to make Policy more dynamic, something like the below scenario ?

The policies should be configurable from UI. For example in below scenario Super Admin should be able to configure the roles for defined policies. 

Role
----
1 Admin
2 User
3 Super Admin

Policy
------
CreateProductPolicy - Should be a (Admin)
ReadProductPolicy   - Should be a (User OR Admin)
UpdateProductPolicy - Should be a (Admin AND User)
DeleteProductPolicy - Should be a (Admin) AND have no other role

DB PolicyRole (Super Admin should be able to update this)
-----------

ID  PolicyName              RoleConfiguration
----------------------------------------------
1   CreateProductPolicy          1
2   ReadProductPolicy           1|2
3   UpdateProductPolicy      1&2
4   DeleteProductPolicy          1*

UserRole
--------
User 1 -> Admin, User
User 2 -> Admin
User 3 -> User

Authorized Users based on Policy
---------------------------------
CreateProductPolicy - 1, 2
ReadProductPolicy   - 1, 2, 3  
UpdateProductPolicy - 1
DeleteProductPolicy - 2

**Comment by phongnguyend** [comment]
The code is now much more easier to support this scenario.
