### ISSUE TITLE
Multi Database Support

### ISSUE THREAD

**Issue by aneesanp123** [phongnguyend/Practical.CleanArchitecture#126]
Is this best practice for multi database for our source code
***************************************************
1. Connection String of Service
***************************************************

"ConnectionStrings": {
    "DBType": "MSSQLSERVER", // MSSQLSERVER, POSTGRESQL, MYSQL
    "BSuit": "Server=.;Database=BSuit.Microservices.Product;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
  },

*************************************************************
2. App Settings
*************************************************************
public class ConnectionStrings
    {
        public string DBType { get; set; } // New Field
        public string BSuit { get; set; }

        public string MigrationsAssembly { get; set; }
    }

**************************************************************
3.     xxxxxxxxxModuleServiceCollectionExtensions
**************************************************************
if (appSettings.ConnectionStrings.DBType == "MSSQLSERVER")
            {
                services.AddDbContext<ProductDbContext>(options => options.UseSqlServer(appSettings.ConnectionStrings.BSuit, sql =>
                {
                    if (!string.IsNullOrEmpty(appSettings.ConnectionStrings.MigrationsAssembly))
                    {
                        sql.MigrationsAssembly(appSettings.ConnectionStrings.MigrationsAssembly);
                    }
                }));
            }
            else if (appSettings.ConnectionStrings.DBType == "POSTGRESQL")
            {
                services.AddDbContext<ProductDbContext>(options => options.UseNpgsql(appSettings.ConnectionStrings.BSuit, sql =>
                {
                    if (!string.IsNullOrEmpty(appSettings.ConnectionStrings.MigrationsAssembly))
                    {
                        sql.MigrationsAssembly(appSettings.ConnectionStrings.MigrationsAssembly);
                    }
                }));
            }

**Comment by phongnguyend** [comment]
Thanks @aneesanp123, however, the database provider (MSSQL/POSTGRESQL) is considered something we should configure explicitly rather than switching back and forth by value in the configuration.
