### ISSUE TITLE
Question: Third party api clients

### ISSUE THREAD

**Issue by rekosko** [phongnguyend/Practical.CleanArchitecture#128]
Hello,

First of all I really like what you are doing and by sharing it with us. Big thanks!
I have one question regarding third party apis. What I mean by that is that we are using Refit in our project. We are defining interfaces that use special attributes from it. Later on that that interfaces are injected into specific repository implementations.
Our project is currently structured as monolith. Right now we've found a place for those interfaces in `Persistence` project but I'm really curious is it really the best place for them?

**Comment by phongnguyend** [comment]
Thanks @rekosko for being interested in this repo.

My assumption is you are using Refit to interact with remote data stores via HTTP?

If that is correct, my personal opinion is Yes, you can keep them in `Persistence` if they are not referenced somewhere else outside `Persistence`.

**Comment by rekosko** [comment]
Yes, that's the case :) Thank you for your feedback about this.
