### ISSUE TITLE
Migration Error

### ISSUE THREAD

**Issue by azizcharfeddine** [phongnguyend/Practical.CleanArchitecture#129]
Hello i m trying to work on the MicroService Project and when i want to make a migration of Identity.Authserver this error apeared
![image](https://user-images.githubusercontent.com/57187596/157406527-8791cc1f-23d0-4fab-951c-67db9d2d980e.png)
can some one help me to resolve that error?

**Comment by lefig** [comment]
I have a similar problem...

"No DbContext named 'PersistedGrantDbContext' was found."

**Comment by phongnguyend** [comment]
Close this as IdentityServers were moved to a separate folder [/src/IdentityServer](/phongnguyend/Practical.CleanArchitecture/tree/master/src/IdentityServer)
