### ISSUE TITLE
Microservice cant get token with postman.

### ISSUE THREAD

**Issue by Deneshiqua** [phongnguyend/Practical.CleanArchitecture#136]
Hello,

Everything is working now on the microservice side.
I have completed the installations.
But I can't get any tokens with postman.

https://localhost:44367/connect/token

```
curl --location --request POST 'https://localhost:44367/connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=password' \
--data-urlencode 'username=phong@gmail.com' \
--data-urlencode 'password=v*7Un8b4rcN@<-RN' \
--data-urlencode 'client_id=ClassifiedAds.WebMVC' \
--data-urlencode 'client_secret=K7gNU3sdo+OL0wNhqoVWhr3g6s1xYv72ol/pe/Unols=' \
--data-urlencode 'scope=openid'
```

When I try to login like this

```
{
     "error": "invalid_client"
}
```

I am encountering the error.
Where am I doing wrong?

Can you help me?

**Comment by phongnguyend** [comment]
Close this as IdentityServers were moved to a separate folder [/src/IdentityServer](/phongnguyend/Practical.CleanArchitecture/tree/master/src/IdentityServer)

Also, make sure to run the migration to seed the clients first
