### ISSUE TITLE
"No DbContext named 'ConfigurationDbContext' was found" error

### ISSUE THREAD

**Issue by Tony20221** [phongnguyend/Practical.CleanArchitecture#183]
The instructions says to run these from Migrator folder
dotnet ef migrations add Init --context AdsDbContext -o Migrations/AdsDb
dotnet ef migrations add Init --context ConfigurationDbContext -o Migrations/ConfigurationDb
dotnet ef migrations add Init --context PersistedGrantDbContext -o Migrations/PersistedGrantDb

The last two gives errors:
No DbContext named 'ConfigurationDbContext' was found.
No DbContext named 'PersistedGrantDbContext' was found.

And the first one while it didn't give any errors, it didn't create any tables in the database.

**Comment by phongnguyend** [comment]
Close this as IdentityServers were moved to a separate folder [/src/IdentityServer](/phongnguyend/Practical.CleanArchitecture/tree/master/src/IdentityServer)
