### ISSUE TITLE
Not possible to get it run

### ISSUE THREAD

**Issue by stopcorp** [phongnguyend/Practical.CleanArchitecture#23]
Hey :-)

Is it possible to make a standalone?

i have vs 2019 & changed:
1. RUN dotnet restore in all DockerFiles needed a solution or Project. i added each
2. changed "ConnectionStrings" in appsettings.json & docker-compose.yml
3. added an docker-compose -f docker-compose.yml up -d batch in the tools path
4. changed all the volumes pathes to my environment in docker-compose.yml
5. tried to install / create / install the certificated in Cert (grpc & ClassifiedAds.IdentityServer)
6. run ClassifiedAds.Migrator for sql tables, etc.

all in all it still not started. maybe better documentation for install or a really standalone one, where nothing has to be changed. just may install 2 certificates, run a tools install, & a initialize mcr.microsoft.com/mssql/server:2017-latest

wonderful architecture, but it wont start :-(

Greetz Stephan

**Comment by stopcorp** [comment]
Not the same as Migrator. The main problem, what i have is, that i only can build it from console. docker-compose -f docker-compose.yml up -d in the ... Practical.CleanArchitecture-master\src\ClassifiedAds.Projects (after changing logging path).

But not from inside VS 2019. No chance. After adding docker-compose to the solution & changed each dockerfile, where *** is webapi, wbmvc, ...:

[...]
COPY ./ClassifiedAds.Projects.sln .
COPY ./docker-compose.dcproj .
RUN dotnet restore ./ClassifiedAds.***/ClassifiedAds.***.csproj

COPY . .
RUN dotnet build ./ClassifiedAds.***/ClassifiedAds.BackgroundServices.csproj -c Release -o /app/build

FROM build AS publish
RUN dotnet publish ./ClassifiedAds.***/ClassifiedAds.***.csproj -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "ClassifiedAds.***.dll"]

Certificate fault or ASPNETCORE_URLS wrong or the containers run, but nothing has started. 

Without debugging feature, i cannot develop. :-(

**Comment by stopcorp** [comment]
Newest version seems to be very very good. Thx for that.

i downloaded it.

1. started VS 2k9 & added docker-compose (by using the old one)
2. changed in in the yml the logging pathes to my directory
3. changed in in the yml the grpc part to: ASPNETCORE_URLS: "https://+:9005" by adding :9005
4. added in the ClassifiedAds.GRPC.csproj under <PropertyGroup>an UserSecretsId>65e4fb04-c01e-453f-83d8-ce2d5399f221</UserSecretsId>& installed the Cert classifiedads.grpc.pfx under Trusted Root in certmgr
5. changed in all dockerfiles the specific: 
	COPY ./ClassifiedAds.Projects.sln .
	COPY ./docker-compose.dcproj .
	RUN dotnet restore ./ClassifiedAds./ClassifiedAds..csproj

Now it built & runs, but still the idsv. tables are not built correctly. Also if i start the Migrator only. Earlier this worked.

**Comment by phongnguyend** [comment]
Great. I close this for now.
