### ISSUE TITLE
Adding Identity Server 4 Admin UI

### ISSUE THREAD

**Issue by phongnguyend** [phongnguyend/Practical.CleanArchitecture#31]
- https://github.com/skoruba/IdentityServer4.Admin
- https://github.com/brunohbrito/JPProject.IdentityServer4.AdminUI

**Comment by stopcorp** [comment]
Error
Sorry, there was an error : unauthorized_client
Unknown client or client not enabled

Client Application Access
Below is the list of applications you have given access to and the names of the resources they have access to.
You have not given access to any applications

**Comment by phongnguyend** [comment]
Hi @stopcorp, 

You can pull the latest code and start the **ClassifiedAds.Migrator** again to seed the Identity Server configuration for client applications automatically.

I've also finished the Admin UI, you can take a look at the **Identity Server** https://localhost:44367 to configure application settings directly via UI.

Cheers,

**Comment by stopcorp** [comment]
Thx. But i decided to set up on an other architecture.
