### ISSUE TITLE
How to publish?

### ISSUE THREAD

**Issue by AnthonyHuang** [phongnguyend/Practical.CleanArchitecture#35]
First, thanks for this repo. I really like it. I have a question on publishing. For example, I want to publish to folder. I use Blazor as the frontend, but I also use BackgroundServer, NotificationServer, IdentityServer. On persistence I change to Sqlite instead of SQL Server. I can run it in VS 2019 without problem. Could you let me know what is the correct way to publish this? Thanks!

**Comment by phongnguyend** [comment]
Thanks @AnthonyHuang for being interested in this repo. Where would you like to deploy the applications to? IIS, Azure App Service or you want to publish them as Docker images and run as containers some where?

**Comment by AnthonyHuang** [comment]
> Thanks @AnthonyHuang for being interested in this repo. Where would you like to deploy the applications to? IIS, Azure App Service or you want to publish them as Docker images and run as containers some where?

My thinking is to publish to a local folder so that I can copy to other computers to run it, but maybe there is a better way to achieve my gold. I cannot use any cloud services though because there is no internet access at the place I want to run this application.  What is your suggestion and how to deploy? Thanks.

**Comment by phongnguyend** [comment]
Close this as instructions are provided in README files.
