### ISSUE TITLE
Question: ClassifiedAds.Monolith vs ClassifiedAds.ModularMonolith

### ISSUE THREAD

**Issue by Hulkstance** [phongnguyend/Practical.CleanArchitecture#41]
I'm curious what the difference between `ClassifiedAds.Monolith` and `ClassifiedAds.ModularMonolith` is?

My favorite architecture is Domain-Driven Design and I like Mediatr and AutoMapper. I'm also thinking about GraphSQL because it's the future and it will replace the REST services.

Which project would you recommend me? Btw, I'm using Angular and IdentityServer4, I don't need the rest stuff like SignalR, Hangfire, etc.

**Comment by erdincyasan** [comment]
In the Modular Monolith architecture, microservices are written separately but run through a single web api. On the Monolith architecture, all microservices are written on the same web api.
If you have a project with a modular monolith structure, you can publish and use the service you want separately whenever you want. It will be much easier to shred. You will not have any difficulties in transitioning to microservice architecture.

**Comment by phongnguyend** [comment]
Thanks @erdincyasan for answering. I close this now.
