### ISSUE TITLE
Incorrect references in ClassifiedAds.GRPC project

### ISSUE THREAD

**Issue by jasper22** [phongnguyend/Practical.CleanArchitecture#44]
Hi 

May be I'm missing something but just doing:

1. `git clone --recursive https://github.com/phongnguyend/Practical.CleanArchitecture.git`
2. `cd Practical.CleanArchitecture/src/ClassifiedAds.Microservices/Services/ClassifiedAds.GRPC`
3. `dotnet build`

will result to error because some projects missing ?????? 

Actually this project reference other projects like this:

```
    <ItemGroup>
      <ProjectReference Include="..\ClassifiedAds.Application\ClassifiedAds.Application.csproj" />
      <ProjectReference Include="..\ClassifiedAds.Infrastructure\ClassifiedAds.Infrastructure.csproj" />
      <ProjectReference Include="..\ClassifiedAds.Persistence\ClassifiedAds.Persistence.csproj" />
    </ItemGroup>
```
and all those above projects are located somewhere else ???

Could you fix those references ? 
May be provide SLN/script file in root folder to just build everything ? 
Add something to documentation on how to actually build those projects from scratch ?

**Comment by phongnguyend** [comment]
Microservices version (#40)  has been supported now. Documentation will be created soon.
