### ISSUE TITLE
More Email and SMS Sending Options

### ISSUE THREAD

**Issue by phongnguyend** [phongnguyend/Practical.CleanArchitecture#51]
https://azure.microsoft.com/en-us/services/communication-services/
https://github.com/Azure-Samples/communication-services-dotnet-quickstarts/
https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/telephony-sms/send?pivots=programming-language-csharp

https://sendgrid.com/
https://github.com/sendgrid/sendgrid-csharp

**Comment by kiquenet** [comment]
https://www.twilio.com/sendgrid/email-api
