### ISSUE TITLE
Running Microservice code

### ISSUE THREAD

**Issue by SaddamBInSyed** [phongnguyend/Practical.CleanArchitecture#58]
@phongnguyend 
Thanks for your great work.

I could not find the "How to Run" guide for Microservice's project. could you please upload the same?

thanks in advance.

**Comment by phongnguyend** [comment]
Thanks @SaddamBInSyed for being interested in this repo.

Basically, You would need to add db migration for all **ClassifiedAds.Services.*.Api** projects (looking at PowerShell.txt or dotnet-cli.txt for the commands) then build and run all executable projects.

I tend to upgrade the Microservices to use Tye and Dapr, after that I will start creating the guideline document.

**Comment by SaddamBInSyed** [comment]
@phongnguyend 
Than you for your response.

Yes ,that document will be greatly helpful for beginners like me.

I was trying to understand your code and learning unknown tech.stacks since week.

I hope I will get latest twch trends and best code practices in this repo.

If possible Please shed some light to balzor app too
Thank you

**Comment by phongnguyend** [comment]
Hi @SaddamBInSyed 

Hope you are well.

Please take a look at the **README.md** file in the [Microservices Folder](https://github.com/phongnguyend/Practical.CleanArchitecture/tree/master/src/Microservices) if you're still interested and would like to run the code.

**Comment by SaddamBInSyed** [comment]
Hi @phongnguyend 

thanks for your help.

Sure, I will refer the same and update you if clarification required,

thank you.
